### ISSUE TITLE
ENOENT error 

### ISSUE THREAD

**Issue by usernamenumber** [tunapanda/funzo-app#5]
Some time after commit 23f1b7b166953df830af24c06ddcde853c62647b, a change was introduced that causes the following error on a fresh clone after running `npm install && bower install && ember serve`:

```
ENOENT, no such file or directory '/Users/brsmith/Documents/Tunapanda/EconApp/VM/funzo-app-unn/tmp/concat_with_maps-input_base_path-biEZ9nzb.tmp/0/bower_components/hammer.js/hammer.js'
Error: ENOENT, no such file or directory '/Users/brsmith/Documents/Tunapanda/EconApp/VM/funzo-app-unn/tmp/concat_with_maps-input_base_path-biEZ9nzb.tmp/0/bower_components/hammer.js/hammer.js'
    at Error (native)
    at Object.fs.statSync (fs.js:797:18)
    at ConcatWithMaps.keyForFile (/Users/brsmith/Documents/Tunapanda/EconApp/VM/funzo-app-unn/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:90:20)
    at Array.map (native)
    at ConcatWithMaps.CachingWriter._conditionalBuild (/Users/brsmith/Documents/Tunapanda/EconApp/VM/funzo-app-unn/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:112:65)
    at /Users/brsmith/Documents/Tunapanda/EconApp/VM/funzo-app-unn/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/node_modules/broccoli-plugin/read_compat.js:61:34
    at lib$rsvp$$internal$$tryCatch (/Users/brsmith/Documents/Tunapanda/EconApp/VM/funzo-app-unn/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:493:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/brsmith/Documents/Tunapanda/EconApp/VM/funzo-app-unn/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:505:17)
    at lib$rsvp$$internal$$publish (/Users/brsmith/Documents/Tunapanda/EconApp/VM/funzo-app-unn/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:476:11)
    at lib$rsvp$asap$$flush (/Users/brsmith/Documents/Tunapanda/EconApp/VM/funzo-app-unn/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1198:9)
```

Reporting the issue now, in case someone more ember-savvy than me sees an obvious fix. Meanwhile I'll see what I can figure out.

**Comment by usernamenumber** [comment]
I can reproduce the problem in OSX and Ubuntu Trusty. 

I tried `npm install hammer` and `npm install hammertime`, in case that might provide the missing `hammer.js`, but the problem persists.

**Comment by usernamenumber** [comment]
`bower install hammerjs` installs `bower_components/hammer.js/hammer.js`, in the clone directory, but ember is looking for it in  `tmp/concat_with_maps-input_base_path-biEZ9nzb.tmp/0/bower_components/hammer.js/hammer.js`

**Comment by usernamenumber** [comment]
Tried `bower cache clear`, but still no luck. 

The random value string after `concat_with_maps-input_base_path-` changes every time I run `ember serve`, so maybe it's an ember thing rather than a bower thing?

**Comment by Jakeii** [comment]
Ok this is caused because of a conflict between `ember-gestures` and `ember-hammertime`, hammertime is the successor anyway and `ember-gestures` was left behind by accident.
